import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import ServiceShell, { MetricCard, ServiceHeading } from '../components/ServiceShell'
import { useAuth } from '../hooks/useAuth'
import { useReveal } from '../hooks/useReveal'
import { demoSurveys, getMySurveys } from '../services/surveyService'

export default function MySurveys() {
  const { user } = useAuth(); const [surveys,setSurveys]=useState([]); const [query,setQuery]=useState(''); const rootRef=useReveal([surveys.length,query])
  useEffect(()=>{getMySurveys(user.id).then(setSurveys).catch(()=>setSurveys([]))},[user.id])
  const display=useMemo(()=>{const base=surveys.length>2?surveys:[...surveys,...demoSurveys.slice(0,Math.max(0,5-surveys.length))];return base.filter(s=>`${s.title} ${s.description}`.toLowerCase().includes(query.toLowerCase()))},[query,surveys])
  const responses=surveys.reduce((sum,s)=>sum+Number(s.response_count||0),0)||189
  return <ServiceShell activePath="/my-surveys"><div ref={rootRef}><ServiceHeading icon="▤" title="내 설문" description="만든 설문을 관리하고 응답 현황과 결과를 확인하세요." action={<Link className="ui-button" to="/surveys/create">＋ 새 설문 만들기</Link>}/><section className="service-metrics"><MetricCard icon="↗" label="진행 중 설문" value={Math.max(1,surveys.length)} unit="개" note="현재 응답을 모집하고 있어요."/><MetricCard tone="mint" icon="✓" label="완료된 설문" value={5} unit="개" note="조사가 완료된 설문이에요."/><MetricCard tone="violet" icon="◎" label="총 응답 수" value={responses} unit="명" note="내 설문에 모인 응답이에요."/><MetricCard tone="amber" icon="▥" label="평균 응답률" value={68} unit="%" note="전체 설문의 평균 응답률이에요."/></section><div className="service-table-tools" data-motion-reveal><input className="service-input" value={query} onChange={e=>setQuery(e.target.value)} placeholder="설문 제목이나 설명으로 검색해보세요."/><select className="service-select"><option>전체 상태</option><option>진행 중</option><option>종료</option></select><select className="service-select"><option>생성일 최신순</option><option>응답 많은순</option></select></div><section className="managed-list">{display.map((survey,index)=>{const progress=Math.min(100,Math.round(Number(survey.response_count||0)/Math.max(1,Number(survey.target_count||1))*100));const isOwned=survey.creator_id===user.id;return <article className="managed-row ui-card" key={`${survey.id}-${index}`} data-motion-reveal style={{'--delay':`${Math.min(index,5)*65}ms`}}><div className="managed-row__title"><span className={`service-tone--${['violet','amber','rose','mint','blue'][index%5]}`}>{['◇','○','▤','◎','✦'][index%5]}</span><div><h2>{survey.title}</h2><p>{survey.description}</p><small>약 {survey.estimated_minutes||5}분 · 응답 {survey.response_count||0}명 · {survey.category||'일반'}</small></div></div><div className="managed-progress"><span>{progress}%</span><div><i style={{'--progress':`${progress}%`}}/></div><small>{survey.response_count||0}명 / {survey.target_count||0}명</small></div><div className="managed-actions"><Link to={`/surveys/${survey.id}`}>{isOwned?'상세보기':'미리보기'}</Link>{isOwned&&survey.response_count>0&&<Link to={`/surveys/${survey.id}/results`}>결과보기</Link>}<button type="button">공유</button></div></article>})}</section></div></ServiceShell>
}
