import { useEffect, useState } from 'react'
import ServiceShell, { ServiceHeading } from '../components/ServiceShell'
import { useAuth } from '../hooks/useAuth'
import { useReveal } from '../hooks/useReveal'
import { getProfile, saveProfile } from '../services/userService'

export default function Settings(){
  const {user,demoMode}=useAuth(); const [profile,setProfile]=useState({name:'',occupation:'',age_group:'20대',region:'서울',interests:[]}); const [notices,setNotices]=useState({email:true,push:true,product:false}); const [visibility,setVisibility]=useState('전체 공개'); const [toast,setToast]=useState(''); const rootRef=useReveal([])
  useEffect(()=>{getProfile(user.id).then(setProfile).catch(()=>{})},[user.id])
  const toggle=(key)=>setNotices(v=>({...v,[key]:!v[key]}))
  const save=async()=>{try{await saveProfile({...profile,id:user.id});setToast(demoMode?'데모 설정을 저장했습니다.':'변경사항을 저장했습니다.')}catch(error){setToast(error.message)}setTimeout(()=>setToast(''),900)}
  return <ServiceShell activePath="/settings"><div ref={rootRef}><ServiceHeading icon="⚙" title="설정" description="계정 정보와 서비스 이용 환경을 관리할 수 있습니다."/><section className="settings-grid">
    <article className="settings-card ui-card" data-motion-reveal><h2>프로필 정보</h2><p>설문 추천에 활용할 기본 정보를 관리합니다.</p><div className="settings-fields"><label>이름<input value={profile.name||''} onChange={e=>setProfile({...profile,name:e.target.value})}/></label><label>이메일<input value={user.email||''} disabled/></label><label>직업<input value={profile.occupation||''} onChange={e=>setProfile({...profile,occupation:e.target.value})}/></label><label>연령대<select value={profile.age_group||'20대'} onChange={e=>setProfile({...profile,age_group:e.target.value})}>{['10대','20대','30대','40대','50대 이상'].map(v=><option key={v}>{v}</option>)}</select></label></div></article>
    <article className="settings-card ui-card" data-motion-reveal style={{'--delay':'60ms'}}><h2>계정 상태</h2><p>현재 계정과 서비스 이용 상태를 확인합니다.</p><div className="settings-row"><div><strong>이용 상태</strong><small>현재 계정은 정상적으로 이용 가능합니다.</small></div><span className="catalog-tag">정상</span></div><div className="settings-row"><div><strong>가입 이메일</strong><small>{user.email}</small></div></div><div className="settings-row"><div><strong>최근 접속</strong><small>오늘 오후 11:00</small></div></div></article>
    <article className="settings-card ui-card" data-motion-reveal><h2>알림 설정</h2><p>필요한 소식을 놓치지 않도록 설정하세요.</p>{[['email','이메일 알림','설문 참여와 결과 안내를 이메일로 받습니다.'],['push','서비스 알림','새로운 설문과 응답 소식을 받습니다.'],['product','업데이트 소식','새 기능과 주요 변경사항을 받습니다.']].map(([key,title,copy])=><div className="settings-row" key={key}><div><strong>{title}</strong><small>{copy}</small></div><button className={`toggle ${notices[key]?'is-on':''}`} type="button" aria-pressed={notices[key]} aria-label={`${title} ${notices[key]?'끄기':'켜기'}`} onClick={()=>toggle(key)}/></div>)}</article>
    <article className="settings-card ui-card" data-motion-reveal style={{'--delay':'60ms'}}><h2>설문 공개 범위</h2><p>새 설문의 기본 공개 범위를 설정합니다.</p>{['전체 공개','조건별 공개','비공개'].map(value=><label className="settings-row" key={value}><div><strong>{value}</strong><small>{value==='전체 공개'?'모든 사용자가 참여할 수 있습니다.':value==='조건별 공개'?'설정한 대상에게만 보여줍니다.':'초대 링크로만 참여할 수 있습니다.'}</small></div><input type="radio" name="visibility" checked={visibility===value} onChange={()=>setVisibility(value)}/></label>)}</article>
    <article className="settings-card ui-card" data-motion-reveal><h2>비밀번호 변경</h2><p>안전한 계정 사용을 위해 비밀번호를 관리하세요.</p><div className="settings-fields"><label>현재 비밀번호<input type="password" placeholder="현재 비밀번호"/></label><label>새 비밀번호<input type="password" placeholder="8자 이상"/></label><label>비밀번호 확인<input type="password" placeholder="다시 입력"/></label></div></article>
    <article className="settings-card ui-card" data-motion-reveal style={{'--delay':'60ms'}}><h2>데이터와 계정</h2><p>내 데이터와 계정 관련 설정입니다.</p><div className="settings-row"><div><strong>설문 데이터 내보내기</strong><small>내가 만든 설문과 응답 요약을 저장합니다.</small></div><button className="ui-button ui-button--secondary" type="button">내보내기</button></div><div className="settings-row"><div><strong>계정 탈퇴</strong><small>탈퇴 전 필요한 데이터를 먼저 확인해주세요.</small></div><button className="ui-button ui-button--secondary" type="button">탈퇴하기</button></div></article>
  </section><div style={{display:'flex',justifyContent:'flex-end',marginTop:'18px'}}><button className="ui-button" type="button" onClick={save}>변경사항 저장 <span>→</span></button></div>{toast&&<div className="service-toast" role="status">✓ {toast}</div>}</div></ServiceShell>
}
